spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: aluno
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: none
  sql:
    init:
      mode: always
      platform: mysql
